name: macos

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
          # - { os: macos-10.15, dc: ldc-latest }
          - { os: macos-latest, dc: ldc-latest  }
        # build: [Debug, Release]
        build: [Release]

    name: "${{matrix.config.os}}:${{matrix.build}}"

    steps:
    - uses: actions/checkout@v2
    - uses: dlang-community/setup-dlang@v1.2.0

    - name: 'Build'
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      run: |
        # Build the project, without unittests
        dub build --compiler=$DC
        # Build and run tests
        dub test -b unittest-cov --compiler=$DC
