name: ubuntu

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: dlang-community/setup-dlang@v1.2.0

    - name: 'Build & Test'
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      run: |
        # Build the project, without unittests
        dub build --compiler=$DC
        # Build and run tests
        dub test -b unittest-cov --compiler=$DC
        # Upload code coverage
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov
